export const mockCategories = [
    { id: '1', name: 'Electronics', description: 'Electronic devices and equipment', createdAt: '2024-01-01' },
    { id: '2', name: 'Furniture', description: 'Office furniture and fixtures', createdAt: '2024-01-01' },
    { id: '3', name: 'Vehicles', description: 'Company vehicles and transportation', createdAt: '2024-01-01' },
    { id: '4', name: 'IT Equipment', description: 'Servers, networking, and IT infrastructure', parentId: '1', createdAt: '2024-01-15' },
    { id: '5', name: 'Office Supplies', description: 'General office supplies', createdAt: '2024-02-01' },
];

export const mockStores = [
    { id: '1', name: 'Main Warehouse', location: 'Building A, Floor 1', managerId: '2', capacity: 1000, currentOccupancy: 756, createdAt: '2024-01-01' },
    { id: '2', name: 'IT Storage', location: 'Building B, Floor 2', managerId: '2', capacity: 500, currentOccupancy: 342, createdAt: '2024-01-15' },
    { id: '3', name: 'Vehicle Depot', location: 'Compound C', managerId: '2', capacity: 50, currentOccupancy: 28, createdAt: '2024-02-01' },
    { id: '4', name: 'Regional Office Store', location: 'Regional HQ', managerId: '2', capacity: 300, currentOccupancy: 187, createdAt: '2024-03-01' },
];

export const mockShelves = [
    { id: '1', storeId: '1', name: 'Shelf A1', code: 'MWH-A1', capacity: 100, currentOccupancy: 85 },
    { id: '2', storeId: '1', name: 'Shelf A2', code: 'MWH-A2', capacity: 100, currentOccupancy: 92 },
    { id: '3', storeId: '1', name: 'Shelf B1', code: 'MWH-B1', capacity: 100, currentOccupancy: 67 },
    { id: '4', storeId: '2', name: 'Server Rack 1', code: 'IT-SR1', capacity: 50, currentOccupancy: 45 },
    { id: '5', storeId: '2', name: 'Server Rack 2', code: 'IT-SR2', capacity: 50, currentOccupancy: 38 },
];

export const mockAssets = [
    {
        id: '1',
        name: 'Dell Latitude 5540',
        code: 'AST-001',
        categoryId: '1',
        storeId: '2',
        shelfId: '4',
        status: 'IN_USE',
        purchaseDate: '2024-03-15',
        purchasePrice: 1200,
        currentValue: 1000,
        assignedTo: '5',
        serialNumber: 'DL5540-2024-001',
        createdAt: '2024-03-15',
        updatedAt: '2025-01-10',
    },
    {
        id: '2',
        name: 'HP ProBook 450',
        code: 'AST-002',
        categoryId: '1',
        storeId: '2',
        status: 'AVAILABLE',
        purchaseDate: '2024-04-20',
        purchasePrice: 980,
        currentValue: 850,
        serialNumber: 'HP450-2024-002',
        createdAt: '2024-04-20',
        updatedAt: '2024-12-01',
    },
    {
        id: '3',
        name: 'Executive Desk',
        code: 'AST-003',
        categoryId: '2',
        storeId: '1',
        shelfId: '1',
        status: 'IN_USE',
        purchaseDate: '2024-01-10',
        purchasePrice: 450,
        currentValue: 400,
        assignedTo: '3',
        createdAt: '2024-01-10',
        updatedAt: '2024-06-15',
    },
    {
        id: '4',
        name: 'Toyota Hilux',
        code: 'AST-004',
        categoryId: '3',
        storeId: '3',
        status: 'MAINTENANCE',
        purchaseDate: '2023-06-01',
        purchasePrice: 35000,
        currentValue: 28000,
        serialNumber: 'TH-2023-001',
        createdAt: '2023-06-01',
        updatedAt: '2025-01-15',
    },
    {
        id: '5',
        name: 'Dell PowerEdge R750',
        code: 'AST-005',
        categoryId: '4',
        storeId: '2',
        shelfId: '4',
        status: 'IN_USE',
        purchaseDate: '2024-02-28',
        purchasePrice: 8500,
        currentValue: 7500,
        serialNumber: 'PE-R750-2024-001',
        createdAt: '2024-02-28',
        updatedAt: '2024-11-20',
    },
    {
        id: '6',
        name: 'Cisco Switch 48-Port',
        code: 'AST-006',
        categoryId: '4',
        storeId: '2',
        shelfId: '5',
        status: 'AVAILABLE',
        purchaseDate: '2024-05-10',
        purchasePrice: 2200,
        currentValue: 2000,
        serialNumber: 'CS48-2024-001',
        createdAt: '2024-05-10',
        updatedAt: '2024-10-05',
    },
    {
        id: '7',
        name: 'Conference Table',
        code: 'AST-007',
        categoryId: '2',
        storeId: '1',
        shelfId: '2',
        status: 'DISPOSED',
        purchaseDate: '2020-03-15',
        purchasePrice: 1200,
        currentValue: 0,
        createdAt: '2020-03-15',
        updatedAt: '2025-01-05',
    },
    {
        id: '8',
        name: 'Lenovo ThinkPad X1',
        code: 'AST-008',
        categoryId: '1',
        storeId: '4',
        status: 'RESERVED',
        purchaseDate: '2024-08-20',
        purchasePrice: 1500,
        currentValue: 1400,
        serialNumber: 'LTX1-2024-001',
        createdAt: '2024-08-20',
        updatedAt: '2025-01-18',
    },
];

export const mockUsers = [
    {
        id: '1',
        email: 'admin@insa.gov',
        name: 'Administrator',
        role: 'admin',
        department: 'IT Administration',
        createdAt: '2024-01-01',
        lastLogin: '2025-01-19',
    },
    {
        id: '2',
        email: 'store.manager@insa.gov',
        name: 'Sarah Johnson',
        role: 'store-manager',
        department: 'Logistics',
        createdAt: '2024-02-15',
        lastLogin: '2025-01-19',
    },
    {
        id: '3',
        email: 'asset.manager@insa.gov',
        name: 'Michael Chen',
        role: 'asset-manager',
        department: 'Asset Management',
        createdAt: '2024-03-10',
        lastLogin: '2025-01-19',
    },
    {
        id: '4',
        email: 'technician@insa.gov',
        name: 'David Williams',
        role: 'technician',
        department: 'Maintenance',
        createdAt: '2024-04-20',
        lastLogin: '2025-01-19',
    },
    {
        id: '5',
        email: 'employee@insa.gov',
        name: 'Emily Brown',
        role: 'employee',
        department: 'Operations',
        createdAt: '2024-05-05',
        lastLogin: '2025-01-19',
    },
    {
        id: '6',
        email: 'auditor@insa.gov',
        name: 'Robert Taylor',
        role: 'auditor',
        department: 'Internal Audit',
        createdAt: '2024-06-12',
        lastLogin: '2025-01-19',
    },
];

export const mockAssignmentRequests = [
    {
        id: '1',
        assetId: '2',
        requesterId: '5',
        status: 'PENDING',
        reason: 'Need laptop for field work assignment',
        requestedAt: '2025-01-18T14:30:00Z',
    },
    {
        id: '2',
        assetId: '6',
        requesterId: '4',
        status: 'APPROVED',
        reason: 'Required for network expansion project',
        requestedAt: '2025-01-15T09:00:00Z',
        processedAt: '2025-01-16T11:30:00Z',
        processedBy: '2',
    },
    {
        id: '3',
        assetId: '8',
        requesterId: '5',
        status: 'REJECTED',
        reason: 'Personal use request',
        requestedAt: '2025-01-10T16:45:00Z',
        processedAt: '2025-01-11T08:15:00Z',
        processedBy: '2',
    },
];

export const mockAssignments = [
    {
        id: '1',
        assetId: '1',
        userId: '5',
        status: 'ACTIVE',
        assignedDate: '2024-01-20',
    },
    {
        id: '2',
        assetId: '3',
        userId: '5',
        status: 'ACTIVE',
        assignedDate: '2024-01-15',
    },
    {
        id: '3',
        assetId: '2',
        userId: '5',
        status: 'PENDING',
        assignedDate: '2025-01-18',
    },
];

export const mockTransferRequests = [
    {
        id: '1',
        assetId: '5',
        fromStoreId: '2',
        toStoreId: '4',
        requesterId: '3',
        status: 'PENDING',
        reason: 'Regional office needs server capacity',
        requestedAt: '2025-01-17T10:00:00Z',
    },
    {
        id: '2',
        assetId: '3',
        fromStoreId: '1',
        toStoreId: '4',
        requesterId: '3',
        status: 'APPROVED',
        reason: 'Office relocation',
        requestedAt: '2025-01-12T14:20:00Z',
        processedAt: '2025-01-13T09:45:00Z',
        processedBy: '2',
    },
];

export const mockMaintenanceTasks = [
    {
        id: '1',
        assetId: '4',
        technicianId: '4',
        type: 'corrective',
        status: 'IN_PROGRESS',
        priority: 'high',
        description: 'Engine maintenance and oil change',
        scheduledDate: '2025-01-15',
        createdAt: '2025-01-14T08:00:00Z',
    },
    {
        id: '2',
        assetId: '5',
        technicianId: '4',
        type: 'preventive',
        status: 'SCHEDULED',
        priority: 'medium',
        description: 'Server firmware update and health check',
        scheduledDate: '2025-01-25',
        createdAt: '2025-01-10T10:30:00Z',
    },
    {
        id: '3',
        assetId: '1',
        technicianId: '4',
        type: 'inspection',
        status: 'COMPLETED',
        priority: 'low',
        description: 'Annual laptop inspection and cleaning',
        scheduledDate: '2025-01-05',
        completedDate: '2025-01-05',
        notes: 'Laptop in good condition, battery replaced',
        createdAt: '2024-12-28T09:15:00Z',
    },
];

export const mockAuditLogs = [
    {
        id: '1',
        userId: '1',
        userName: 'John Doe',
        userRole: 'Admin',
        action: 'Updated Role Permission',
        entityType: 'Role',
        entityId: '8821',
        target: 'role_id: 8821',
        details: 'Updated permission set for admin role',
        status: 'Success',
        timestamp: '2023-10-24T14:32:05Z',
    },
];

export const mockNotifications = [
    {
        id: '1',
        userId: '1',
        title: 'New Asset Request',
        message: 'Emily Brown requested a laptop assignment',
        type: 'info',
        read: false,
        createdAt: '2025-01-19T10:30:00Z',
    },
];

export const assetsByStatusData = [
    { status: 'In Use', value: 523, fill: 'var(--chart-1)' },
    { status: 'Available', value: 189, fill: 'var(--chart-2)' },
    { status: 'Maintenance', value: 45, fill: 'var(--chart-3)' },
    { status: 'Reserved', value: 67, fill: 'var(--chart-4)' },
    { status: 'Disposed', value: 23, fill: 'var(--chart-5)' },
];

export const assetsTrendData = [
    { month: 'Jul', assets: 720, requests: 45 },
    { month: 'Aug', assets: 450, requests: 52 },
    { month: 'Sep', assets: 400, requests: 38 },
    { month: 'Oct', assets: 805, requests: 61 },
    { month: 'Nov', assets: 825, requests: 48 },
    { month: 'Dec', assets: 340, requests: 55 },
    { month: 'Jan', assets: 347, requests: 42 },
];

export const maintenanceByTypeData = [
    { type: 'Preventive', count: 34, fill: 'var(--chart-1)' },
    { type: 'Corrective', count: 18, fill: 'var(--chart-2)' },
    { type: 'Inspection', count: 25, fill: 'var(--chart-3)' },
];

export const mockDashboardStats = {
    totalAssets: 847,
    assetsInUse: 523,
    pendingRequests: 12,
    maintenanceTasks: 8,
    totalStores: 4,
    totalUsers: 156,
};
